### PR TITLE
Introduce Cable Handshake Implementation

### PR DESCRIPTION
**Pull request by mycognosist**
Much much WIP.

- [x] Version exchange
- [x] Noise handshake negotiation
- [x] Basic write and read methods
- [x] Static key retrieval 
- [x] Fragmentation support
- [x] End-of-stream marker support 
- [x] Comprehensive unit tests
- [x] Examples
  - [x] TCP stream (synchronous)
  - [x] TCP stream (asynchonous) 
  - [x] Unix socket (synchronous)
- [x] Integration tests
  - [x] Synchronous TCP
  - [x] Asynchronous TCP 
- [x] Benchmarks
  - [x] Synchronous handshake
  - [x] Synchronous message exchange
- [x] Comprehensive documentation
  - [x] README
  - [x] Doc comments
  - [x] Code comments 
- [x] Licensing
- [x] REUSE compliance
- [x] Interoperability tests

### CODE REVIEW

**Comment by cblgh** [comment]
@mycognosist 

> CC-BY-4.0 is being used for flamegraph.svg.license.

i think the error is occuring because flamegraph.svg is in your .gitignore / not included in the repo?

**Comment by mycognosist** [comment]
> @mycognosist
> 
> > CC-BY-4.0 is being used for flamegraph.svg.license.
> 
> i think the error is occuring because flamegraph.svg is in your .gitignore / not included in the repo?

Yes! REUSE wizard! Thanks :D

> Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)

**Comment by mycognosist** [comment]
Alrighty, I think everything is now complete :)

I've included a slightly cursed bash script to do the Rust-TypeScript interop testing.

Just rechecked reuse compliance and we're good to go.

**Review by cblgh — APPROVED** [review]
🙏 AMAZING

**Pull request merged**
